[versions]
agp = "8.13.0"
glide = "5.0.5"
gscore = "1.1.0"
gson = "2.13.2"
kotlin = "2.1.10"
coreKtx = "1.16.0"
appcompat = "1.7.1"
activityKtxVersion = "1.10.0"
fragmentKtxVersion = "1.8.9"
kotlinxCoroutinesPlayServices = "1.10.2"
material = "1.13.0"
activity = "1.10.0"
constraintlayout = "2.2.1"

coil3 = "3.3.0"

minSdk = "24"
targetSdk = "35"
playServicesMlkitFaceDetection = "17.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtxVersion" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtxVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gscore = { module = "com.github.vtabk2:GsCore", version.ref = "gscore" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
coil3-core = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
play-services-mlkit-face-detection = { group = "com.google.android.gms", name = "play-services-mlkit-face-detection", version.ref = "playServicesMlkitFaceDetection" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

